#!/usr/bin/ruby

if ARGV.count == 3
  project = ARGV[0]
  frames  = ARGV[1]
  delay   = ARGV[2]

  [].tap do |command|
    command << '/usr/local/Cellar/graphicsmagick/1.3.17/bin/gm convert -loop 100'
    (1..frames).each { |i| command << "-delay #{delay} /tmp/#{project}/#{i}.png" }
    command << "/tmp/#{project}.gif"

    system command.join(' ')
  end
else
  puts 'usage:', './make_gif project frames delay'
end


